name: Deploy IAC

on:
  workflow_dispatch:

env: 
    REGISTRYNAME: nvg46g5woyax4mpnpreg.azurecr.io
    REPOSITORYNAME: techboost/dotnetcoreapp

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      id: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=dev

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ steps.deploy.outputs.application_name }}
        images: ${{ env.REGISTRYNAME }}/${{ env.REPOSITORYNAME }}:latest

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}

  build-and-deploy-test:
    runs-on: ubuntu-latest
    needs: [ build-and-deploy-dev ]
    steps:

        # Checkout code
    - uses: actions/checkout@main

        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=test

        # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    needs: [ build-and-deploy-dev, build-and-deploy-test ]
    steps:

        # Checkout code
    - uses: actions/checkout@main

        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=prod

        # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}